In [1]:
import torch
from model_trial import model_trial_v1

In [2]:
model_weight = torch.load("save_temp/softmax_conv_model/model.th")['state_dict']

In [24]:
model_weight2 = torch.load("save_temp/ResNet20_plug4_1//model.th")['state_dict']

In [25]:
model_weight2.keys()

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'block1_conv1.weight', 'block1_bn1.weight', 'block1_bn1.bias', 'block1_bn1.running_mean', 'block1_bn1.running_var', 'block1_bn1.num_batches_tracked', 'block1_conv2.weight', 'block1_bn2.weight', 'block1_bn2.bias', 'block1_bn2.running_mean', 'block1_bn2.running_var', 'block1_bn2.num_batches_tracked', 'block2_conv1.weight', 'block2_bn1.weight', 'block2_bn1.bias', 'block2_bn1.running_mean', 'block2_bn1.running_var', 'block2_bn1.num_batches_tracked', 'block2_conv2.weight', 'block2_bn2.weight', 'block2_bn2.bias', 'block2_bn2.running_mean', 'block2_bn2.running_var', 'block2_bn2.num_batches_tracked', 'block3_conv1.weight', 'block3_bn1.weight', 'block3_bn1.bias', 'block3_bn1.running_mean', 'block3_bn1.running_var', 'block3_bn1.num_batches_tracked', 'block3_conv2.weight', 'block3_bn2.weight', 'block3_bn2.bias', 'block3_bn2.running_mean', 'block3_bn2.running_var', 'block3_bn2.nu

In [5]:
model_weight.keys()

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'block1_conv1.weight', 'block1_bn1.weight', 'block1_bn1.bias', 'block1_bn1.running_mean', 'block1_bn1.running_var', 'block1_bn1.num_batches_tracked', 'block1_conv2.weight', 'block1_bn2.weight', 'block1_bn2.bias', 'block1_bn2.running_mean', 'block1_bn2.running_var', 'block1_bn2.num_batches_tracked', 'block2_conv1.weight', 'block2_bn1.weight', 'block2_bn1.bias', 'block2_bn1.running_mean', 'block2_bn1.running_var', 'block2_bn1.num_batches_tracked', 'block2_conv2.weight', 'block2_bn2.weight', 'block2_bn2.bias', 'block2_bn2.running_mean', 'block2_bn2.running_var', 'block2_bn2.num_batches_tracked', 'block3_conv1.weight', 'block3_bn1.weight', 'block3_bn1.bias', 'block3_bn1.running_mean', 'block3_bn1.running_var', 'block3_bn1.num_batches_tracked', 'block3_conv2.weight', 'block3_bn2.weight', 'block3_bn2.bias', 'block3_bn2.running_mean', 'block3_bn2.running_var', 'block3_bn2.nu

In [33]:
a = model_weight['conv1.weight']

In [42]:
a.size()

torch.Size([16, 3, 3, 3])

In [44]:
torch.min(a, dim=-1).values.unsqueeze(-1).size()

torch.Size([16, 3, 3, 1])

In [39]:
a / a.min(dim=-1).values

RuntimeError: The size of tensor a (3) must match the size of tensor b (16) at non-singleton dimension 1

In [28]:
import numpy as np

In [30]:
(np.e) ** (-5.0804e-02)

0.9504649434059966

In [19]:
def get_softmax_weight(data):
    size = data.size()
    temp = data.view(size[0], size[1], size[2] * size[3])
    att = torch.nn.Softmax(dim=2)(temp)
    return att

In [32]:
get_softmax_weight(model_weight2['block3_conv1.weight'] * 100)[1, 1]

tensor([0.0342, 0.0068, 0.0820, 0.0262, 0.0104, 0.0089, 0.0175, 0.8099, 0.0041],
       device='cuda:0')

In [23]:
get_softmax_weight(model_weight['block3_conv1.weight']).std(dim=-1)

tensor([[0.0093, 0.0049, 0.0100, 0.0065, 0.0129, 0.0050, 0.0058, 0.0058, 0.0065,
         0.0041, 0.0139, 0.0045, 0.0033, 0.0070, 0.0083, 0.0060],
        [0.0073, 0.0032, 0.0048, 0.0101, 0.0045, 0.0038, 0.0101, 0.0066, 0.0048,
         0.0055, 0.0049, 0.0053, 0.0040, 0.0070, 0.0050, 0.0038],
        [0.0060, 0.0081, 0.0066, 0.0099, 0.0043, 0.0053, 0.0115, 0.0073, 0.0098,
         0.0033, 0.0061, 0.0067, 0.0039, 0.0067, 0.0108, 0.0054],
        [0.0092, 0.0106, 0.0041, 0.0098, 0.0087, 0.0064, 0.0096, 0.0099, 0.0088,
         0.0095, 0.0110, 0.0139, 0.0068, 0.0086, 0.0063, 0.0025],
        [0.0043, 0.0080, 0.0049, 0.0096, 0.0095, 0.0061, 0.0115, 0.0053, 0.0041,
         0.0034, 0.0059, 0.0072, 0.0062, 0.0086, 0.0081, 0.0018],
        [0.0029, 0.0056, 0.0046, 0.0064, 0.0028, 0.0062, 0.0148, 0.0128, 0.0107,
         0.0030, 0.0065, 0.0077, 0.0058, 0.0070, 0.0137, 0.0036],
        [0.0037, 0.0033, 0.0238, 0.0063, 0.0114, 0.0064, 0.0032, 0.0043, 0.0015,
         0.0039, 0.0157, 0.0054, 0.00

In [14]:
model = model_trial_v1(100)
model.load_state_dict(torch.load("save_temp/ResNet20_plug4_123/model.th")['state_dict'])

<All keys matched successfully>

In [43]:
model.plug1.conv1.weight[:, :, 0, 0].std()

tensor(0.0294, grad_fn=<StdBackward0>)

In [44]:
model.plug1.conv2.weight[:, :, 0, 0].std()

tensor(0.0305, grad_fn=<StdBackward0>)

In [45]:
model.plug2.conv1.weight[:, :, 0, 0].std()

tensor(0.0324, grad_fn=<StdBackward0>)

In [46]:
model.plug2.conv2.weight[:, :, 0, 0].std()

tensor(0.0334, grad_fn=<StdBackward0>)

In [47]:
model.plug3.conv2.weight[:, :, 0, 0].std()

tensor(0.0676, grad_fn=<StdBackward0>)

In [48]:
model.plug3.conv1.weight[:, :, 0, 0].std()

tensor(0.0833, grad_fn=<StdBackward0>)

In [32]:
model_2 = torch.load("save_temp/ResNet20_plug4_1/model.th")['state_dict']

In [50]:
model_2['plug1.conv1.weight'][:, :, 0, 0].std()

tensor(0.0658, device='cuda:0')

In [51]:
model_2['plug1.conv2.weight'][:, :, 0, 0].std()

tensor(0.0554, device='cuda:0')

In [11]:
model_dict.state_dict()

AttributeError: '_IncompatibleKeys' object has no attribute 'state_dict'

In [7]:
weights = torch.load("save_temp/ResNet20_plug4_123/model.th")['state_dict']

In [8]:
weights

OrderedDict([('conv1.weight',
              tensor([[[[-3.7514e-01, -1.2922e-01, -3.3905e-01],
                        [ 5.3782e-01,  1.3543e+00, -1.0767e-01],
                        [ 1.8492e-02,  4.9350e-01, -3.5153e-01]],
              
                       [[ 1.0669e-01, -1.8520e-01,  1.3247e-01],
                        [-3.7987e-01, -4.3377e-01, -2.6069e-01],
                        [ 2.6018e-02, -2.4037e-01,  1.2788e-01]],
              
                       [[ 3.2171e-01,  2.2483e-01,  2.4396e-01],
                        [-2.4167e-01, -5.4766e-01,  2.1477e-01],
                        [ 1.8948e-02, -4.1166e-01,  2.6294e-01]]],
              
              
                      [[[ 2.7955e-01,  3.1833e-01,  1.3752e-01],
                        [ 6.7456e-02, -5.2068e-02, -6.5483e-02],
                        [-1.8116e-01, -3.6739e-01, -1.3898e-01]],
              
                       [[ 3.5726e-01,  4.1500e-01,  1.7439e-01],
                        [ 3.9130e-02, -9.7159